### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by pietercolpaert**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/zOPRa8).

### CODE REVIEW

**Comment by Tjoosten** [comment]
Alright. Was fixing this to PSR-2 standards. Lol

**Comment by pietercolpaert** [comment]
Well, this will save you some work I presume? ;)

**Comment by Tjoosten** [comment]
Indeed. But now i've got nothing to do. I'm hungry for commits on iRail :)

**Comment by pietercolpaert** [comment]
@brechtvdv Feel free to use styleci to create a new pull request yourself if you don't feel like merging this ;) To me it sounds great to comply a code style.

**Comment by brechtvdv** [comment]
Yes, love the idea of using styleci. I will merge when I have time to test that everything still works

**Pull request closed without merging**
